### ISSUE TITLE
Effects.elm not working

### ISSUE THREAD

**Issue by CedricRaison** [sporto/elm-tutorial-assets#2]
Hi,
I was doing the tutorial and didn't find my issue on the effects.elm, so I past the code from github and I still got the same issue.

```
I cannot find find module 'Effects'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

```

I use elm 0.16.

Edit: Just need to install the Effects package. I thought it was already in the basic like Signal and task.
You should update the tuto, many future users will have the same problem.
`elm package install evancz/elm-effect`

**Comment by sporto** [comment]
Please open this in https://github.com/sporto/elm-tutorial
