### ISSUE TITLE
some error in Safari

### ISSUE THREAD

**Issue by yarigpopov** [sporto/elm-tutorial-assets#3]
When I open this link in Safari on Macbook
http://www.elm-tutorial.org/010_foundations/hello.html

and then mouseover the lesson the text disappears
<img width="1087" alt="screen shot 2016-03-27 at 17 57 34" src="https://cloud.githubusercontent.com/assets/3491833/14066284/bbce345c-f445-11e5-8720-4f0a2c5e711e.png">

Same in Chrome works fine

**Comment by sporto** [comment]
I couldn't replicate this on Safari 9.1 here, which version are you using?

If there is an issue it will be with the gitbook viewer, out of my hands really, so I don't think I can do anything about it. Thanks for reporting this anyway.

**Comment by yarigpopov** [comment]
Just rechecked. Everything working fine now
